require 'gamefic/standard/actions/nil'
require 'gamefic/standard/actions/attack'
require 'gamefic/standard/actions/drop'
require 'gamefic/standard/actions/enter'
require 'gamefic/standard/actions/open'
require 'gamefic/standard/actions/close'
require 'gamefic/standard/actions/lock'
require 'gamefic/standard/actions/unlock'
require 'gamefic/standard/actions/go'
require 'gamefic/standard/actions/insert'
require 'gamefic/standard/actions/inventory'
require 'gamefic/standard/actions/leave'
require 'gamefic/standard/actions/look'
require 'gamefic/standard/actions/search'
require 'gamefic/standard/actions/place'
require 'gamefic/standard/actions/quit'
require 'gamefic/standard/actions/take'
require 'gamefic/standard/actions/move'
require 'gamefic/standard/actions/talk'
require 'gamefic/standard/actions/wait'
require 'gamefic/standard/actions/give'
require 'gamefic/standard/actions/repeat'
require 'gamefic/standard/actions/save-restore-undo'
require 'gamefic/standard/actions/pronouns'

module Gamefic
  module Standard
    module Actions
      include Nil
      include Attack
      include Drop
      include Enter
      include Open
      include Close
      include Lock
      include Unlock
      include Go
      include Insert
      include Inventory
      include Leave
      include Look
      include Search
      include Place
      include Quit
      include Take
      include Move
      include Talk
      include Wait
      include Give
      include Repeat
      include SaveRestoreUndo
      include Pronouns
      include Gamefic::What
    end
  end
end
